<?php

declare(strict_types=1);

namespace Gemini\Data;

use Gemini\Contracts\Arrayable;

/**
 * This type has no fields.
 * Tool that executes code generated by the model, and automatically returns the result to the model.
 * See also ExecutableCode and CodeExecutionResult which are only generated when using this tool.
 *
 * https://ai.google.dev/api/caching#CodeExecution
 */
final class CodeExecution implements Arrayable
{
    public function __construct(
    ) {}

    public static function from(): self
    {
        return new self;
    }

    public function toArray(): array
    {
        return [];
    }
}
